### ISSUE TITLE
What are Virtual Hosts

### ISSUE THREAD

**Issue by davidgatti** [zoom/api-v1#21]
Hi @ joshuawoodward, I'm working to implement the Zoom API with a client product. Going over the documentation, and API I still miss some crucial information how to create a proper meeting. I fail to understand what is a "Virtual Host". My questions are:

- What is a Virtual Host?
- How should it be used?

Another thing, what should be proper way to make a meeting. My clients have 2 scenarios:

- (1 on 1), when two people want to just have a video chat
- (Many people), when more the 2 people have to discuss something.

In both cases should I just use the Meeting API? And also:

- Why do I have to provide a `host_id`, the user of my clients don't have a Zoom account nor we want them to force them to make one. Right now I use the host_id of my client, but then I get a message that the host has not joined yet, and the users are confused.

Before I finish, 

- how long will the video recordings stay on your servers? Is there a limit?
- do I have to delete a meeting when the webhook tells me it is over?

This is all the info that I miss from the documentation, I hope you can shad some light, so I can understand exactly how to take advantage of Zoom.

David.

**Comment by joshuawoodward** [comment]
@davidgatti 

What is a Virtual Host?
How should it be used?
A virtual host is a host not tied to a real person. Every meeting is required to have a host set, so you can create a "virtual" user if you're not going to tie that meeting to a real user.

what should be proper way to make a meeting. My clients have 2 scenarios ... In both cases should I just use the Meeting API?
Yes

Why do I have to provide a host_id, the user of my clients don't have a Zoom account nor we want them to force them to make one?
Every meeting requires a host, this is how zoom licensing works, you can only have one concurrent meeting per host. Are you on the API/minute plan?

how long will the video recordings stay on your servers? Is there a limit?
As long as you're a subscriber, they will be there. There is not a time limit, however a capacity limit, the limit depends on how much storage space you are subscribed to.

do I have to delete a meeting when the webhook tells me it is over?
No.. not sure what you're trying to accomplish - if you going to delete right afterwards, why record them at all?

**Comment by davidgatti** [comment]
Thank you for the answers, and I have some follow up questions:

- How to do you Create a Virtual Host with the API, as far as I can see in the user API I see no option for that
- Can I have just one Virtual Host and use it for multiple meetings or do I have to have one for Each meeting?
- Not sure which plan I'm on I have to check with my client
- Regarding this sentence: `if you going to delete right afterwards, why record them at all?` what dose the deletion of a meeting have to do with recording them? Right now this is what goes through my mind: If I create a meeting, and it is over, to have a clean account with unused stuff, I think it be better to clean after myself.

**Comment by joshuawoodward** [comment]
How to do you Create a Virtual Host with the API, as far as I can see in the user API I see no option for that
Create User. The user is "virtual", not connected to a real person.

Can I have just one Virtual Host and use it for multiple meetings or do I have to have one for Each meeting?
No, you need # of virtual hosts for the # of meetings you plan on holding concurrently.

Regarding this sentence: if you going to delete right afterwards, why record them at all? what dose the deletion of a meeting have to do with recording them? Right now this is what goes through my mind: If I create a meeting, and it is over, to have a clean account with unused stuff, I think it be better to clean after myself.
Sorry read this as delete recording. You don't need to delete a meeting after it takes place, this is used to delete an upcoming meeting that is no longer going to take place (which is not required either)

**Comment by davidgatti** [comment]
OK, nice last thing in this case:

So, to create a virtual user I should use this endpoint `https://zoom.github.io/api/#create-a-user`, and set `action` to `custCreate` to get a virtual one?

**Comment by joshuawoodward** [comment]
Yes. However, that endpoint is only available to those on the API pre minute plan.

**Comment by davidgatti** [comment]
Hmm.. ok we are not on the per minute plan.
