### ISSUE TITLE
CRITICAL Cloud auto recording not working anymore

### ISSUE THREAD

**Issue by delmicio** [zoom/api-v1#22]
Hi, you had made some changes on v1 that broke our implementations.

This are the parameters we have always use with API v1:
```
disable_recording: false
enable_cmr: true
enable_cloud_auto_recording: true
enable_auto_delete_cmr: true
auto_delete_cmr_days: 15
enable_record_audio_file: false
```

This was working fine but since Nov 6 our recordings are not being processed.
We are missing 8.000 recordings. This is CRITICAL since we are receiving over 100 complaints per day.

Please revert your changes on V1 or fix this.

**Comment by delmicio** [comment]
@joshuawoodward

**Comment by joshuawoodward** [comment]
I see that is option is still part of the API https://github.com/zoom/api-v1/search?utf8=%E2%9C%93&q=enable_cloud_auto_recording&type=

Also don't see any changes in the actual API source code.. What is exactly the problem you are experiencing? @delmicio

**Comment by joshuawoodward** [comment]
I see that there were some updates in the release notes https://support.zoom.us/hc/en-us/articles/204758419-New-Updates-for-Web (https://support.zoom.us/hc/en-us/articles/115005269866) but not aware of what changes could affect this.. @harrisyang

**Comment by delmicio** [comment]
@joshuawoodward We have hundreds of meetings recording stuck on "processing..."
I'll check that article.

**Comment by joshuawoodward** [comment]
@delmicio so are the meetings being recorded, just not completing processing?

Meaning, a meeting you create.. when meeting is started, recording starts automatically, just the recording never finishes processing?

**Comment by delmicio** [comment]
@joshuawoodward yes, that is the current issue. Meetings recordings starts but are not finishing.

**Comment by joshuawoodward** [comment]
Not an issue with the API.. will work over email with you @delmicio
